### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by Ashwolaa** [Uninett/eduroam-supplicant-win#58]
Hello, 
after connecting for the first time with the geteduroam app on a Windows11, I missclicked and did not give it access to the network list.

Now I am facing this error which I do not know how to solve. 
![image](https://github.com/user-attachments/assets/79f3e6a7-535f-49b5-90b0-726d0453756e)

I tried to reset my network but this did not help.

Any insights?

Thanks!

**Comment by pauldekkers** [comment]
I'm not aware of any network list permission dialog. Is it possible to reproduce on a different client, and share a screenshot of that dialog?

I kind of wonder if this is something specific to your profile. Do other profiles give you the same message?

You could try to download getgovroam, and manually load your eduroam's .eap-config into it - it's a different executable/App, it shouldn't share the permissions.

**Comment by Ashwolaa** [comment]
This is quite confusing. I juste completely reinstalled the windows as it is a new apparel to make it appear again. However, now the error is the following
![image](https://github.com/user-attachments/assets/f971f4d5-b5a8-4bfb-9663-af34e89d6a09)

Nevertheless, I am able to properly connect onto the eduroam wifi. I am quite puzzled but it seems to work now.

**Comment by Ashwolaa** [comment]
I

**Comment by pauldekkers** [comment]
No need to re-open, but if you can still share what version of the App you're on, we can take archive this in case we stumble upon this again.

**Comment by jornane** [comment]
Hi @Ashwolaa, I see you closed this issue already, but this seems to be something that Microsoft changed in Windows 11 24H2. The app checks if the eduroam network is in-range, since 24H2 this requires the Location permission. I've created a test-version (only ARM64 so far) #60 that doesn't use Windows APIs that require Location access.

If you have this problem, you can go into **Settings** -> **Privacy & security** -> **Location**. In there, make sure **Location services** is **on**, and that **Let desktop apps access your location** is also **on**.

We're working to make sure this permission is not needed anymore in a future version of geteduroam for Windows, but the current version needs this permission in order to function.

**Comment by jornane** [comment]
Update: This was already fixed in [v4.2.1](https://github.com/geteduroam/windows-app/releases/tag/v4.2.1), we seem to have forgotten to include it in the changelog as the issue was closed already.
